### ISSUE TITLE
combobox ui bugs

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-combobox#35]
## Describe the bug

These are the bugs Erika found when doing a UI review of the auroized fly website page.  June and I have a branch with a fix to #34 but these are the remaining ones that are showing in combobox...

- [x] Blue border thickness in active state doesn't match spec/auro-input https://github.com/AlaskaAirlines/auro-dropdown/issues/127
- [x] #34 
- [x] Click into field, click X, then the From/To label is no longer aligned properly
- [x] Erroring prior to submission - noverify needs to be passed down to input from combobox #37

The one below is weird because it works perfect for me but not on Erika or June's screen.
- [x] The bolding of the letters in the menu that match the entered string - try light weight for menu items with book for the typed letters

For this let's implement flight search's city API so we can validate with real data.
- [x] How is the sorting within the menu happening? Should function like the homepage widget today, but when you start typing "SE" the first few items in the menu don't have an 'S' and 'Seattle ...' is far down the list

Let's refine this list next week and break up any into separate issues if necessary.

**Comment by leeejune** [comment]
https://www.figma.com/file/3TQhiKjQqQOKYqaqcO1zj2/Dropdown?node-id=906%3A753

Here is the blueprint!

**Comment by blackfalcon** [comment]
This issue is difficult to follow. Some of this is done and others are not? I don't see a branch associated to this issue... nothing is really specifically assigned to anyone? 

@jason-capsule42 and I are listed as assignees, but it's stated that @braven112 and @jason-capsule42 are working on things? 

Please help to define what work needs to be done and who is expected to do it.
